include $(ANDROID_BUILD_TOP)/bootable/recovery/safestrap/devices/common/safestrap-common.mk
include $(ANDROID_BUILD_TOP)/bootable/recovery/safestrap/devices/samsung/msm8998-common/safestrap-msm8998-common.mk


# Virtual partition size default (in mb)
BOARD_DEFAULT_VIRT_SYSTEM_SIZE := 5120
BOARD_DEFAULT_VIRT_SYSTEM_MIN_SIZE := 4700
BOARD_DEFAULT_VIRT_SYSTEM_MAX_SIZE := 5120
BOARD_DEFAULT_VIRT_DATA_SIZE := 4000
BOARD_DEFAULT_VIRT_DATA_MIN_SIZE := 1000
BOARD_DEFAULT_VIRT_DATA_MAX_SIZE := 16000
BOARD_DEFAULT_VIRT_CACHE_SIZE := 300
BOARD_DEFAULT_VIRT_CACHE_MIN_SIZE := 300
BOARD_DEFAULT_VIRT_CACHE_MAX_SIZE := 1000

SS_TWRP_PRINT_SCREENINFO := true
TWRP_EVENT_LOGGING := false

